services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackoverflow_be_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./stackoverflow_be
      dockerfile: Dockerfile.dev
    environment:
      MIX_ENV: dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: stackoverflow_be_dev
      DB_PORT: "5432"
    volumes:
      - ./stackoverflow_be:/app
      - deps:/app/deps
      - _build:/app/_build
      - node_modules_be:/app/assets/node_modules
    command: sh -c "mix ecto.setup || true && mix phx.server"
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app_net

  frontend:
    build:
      context: ./stackoverflow_fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./stackoverflow_fe:/app
      - node_modules_fe:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - app_net
    depends_on:
      - backend

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile.ollama
    container_name: local_llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - app_net
    env_file:
      - .env


volumes:
  db_data:
  deps:
  _build:
  node_modules_be:
  node_modules_fe:
  ollama_models:


networks:
  app_net:
