services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./stackoverflow_be
      dockerfile: Dockerfile.dev
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/dev_db
    volumes:
      - ./stackoverflow_be:/app
      - deps:/app/deps
      - _build:/app/_build
      - node_modules_be:/app/assets/node_modules
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app_net

  frontend:
    build:
      context: ./stackoverflow_fe
      dockerfile: Dockerfile
    volumes:
      - ./stackoverflow_fe:/app
      - node_modules_fe:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_net
    depends_on:
      - backend

volumes:
  db_data:
  deps:
  _build:
  node_modules_be:
  node_modules_fe:

networks:
  app_net:
