FROM hexpm/elixir:1.18.3-erlang-26.2.2-ubuntu-jammy-20240109

# Install Node.js and dependencies
RUN apt-get update && \
    apt-get install -y build-essential git curl npm && \
    mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

# Install JS deps
WORKDIR /app/assets
RUN npm install

# Default back to project root
WORKDIR /app
